apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ipmapper-admin
  labels:
    app: ipmapper-admin
    chart: {{ include "ipmapper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.admin.replicaCount }}
  selector:
    matchLabels:
      app: ipmapper-admin
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: ipmapper-admin
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: MONGO_URL
            value: "mongodb://mongo-service:27017/logger"
          - name: MAXMIND_KEY
            valueFrom:
              secretKeyRef:
                name: ipmapper-secrets
                key: maxMindKey
          - name: MAXMIND_ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                name: ipmapper-secrets
                key: maxMindAccount
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: ipmapper-secrets
                key: jwtKey
          - name: ENABLE_USER_CONTROLLER
            value: "true"
          ports:
            - name: http
              containerPort: {{ .Values.admin.port }}
              protocol: TCP
            - name: management
              containerPort: {{ .Values.managementPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.managementPort }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.managementPort }}
          resources:
{{ toYaml .Values.admin.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      {{- end }}
