# Default values for ipmapper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: jaymell/ipmapper
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

managementPort: 8081

service:
  type: ClusterIP
  port: 8080

admin:
  type: ClusterIP
  port: 8080
  replicaCount: 1
  resources:
    limits:
     cpu: 50m
     memory: 128Mi
    requests:
     cpu: 50m
     memory: 128Mi

ingress:
  enabled: true
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - ipmapper.jaymell.net
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.

nodeSelector: {}

tolerations: []

affinity: {}
